apiVersion: v1
kind: Pod
metadata:
  name: jekyll-ea-dev-pod
  labels:
    app: jekyll-ea-dev-pod
  annotations:
    bind-mount-options: /home/jmk/Repositories/enterprise-architecture-patterns:Z
spec:
  containers:
    - name: jekyll-dev
      image: ghcr.io/bretfisher/jekyll-serve:latest
      ports:
        - containerPort: 4000
          hostPort: 4000
      volumeMounts:
        - name: site
          mountPath: /site
        - name: bundle-cache
          mountPath: /usr/local/bundle
  volumes:
    - name: site
      hostPath:
        path: /home/jmk/Repositories/enterprise-architecture-patterns
        type: Directory
    - name: bundle-cache
      hostPath:
        path: /home/jmk/.cache/jekyll-bundle
        type: DirectoryOrCreate
