apiVersion: v1
kind: Pod
metadata:
  name: jekyll
spec:
  volumes:
    - name: jekyll-ea-shared
      hostPath:
        path: /home/jmk/Repositories/enterprise-architecture-patterns
        type: Directory
        selinuxRelabel: "z"

  containers:
    - name: jekyll-dev
      image: ghcr.io/bretfisher/jekyll-serve:latest
      ports:
        - containerPort: 4000
          hostPort: 4000
      volumeMounts:
        - name: jekyll-ea-shared
          mountPath: /site
          